tonioni/WinUAE

- qemuvga/lsi53c710.cpp
I haven't done any research on this one, so it is more of a question than a pull request (but pull if the answer is true ;)):
Is lsi_scsi_info supposed to use lsi710_* functions here?
> lsi53c710: use lsi710_* functions

- ethernet.cpp
- include/ethernet.h
- include/uae/slirp.h
- od-win32/sysconfig.h
- od-win32/win32_uaenet.cpp
- od-win32/winuae_msvc14/winuae_msvc.vcxproj
- od-win32/winuae_msvc14/winuae_msvc.vcxproj.filters
- slirp_uae.cpp
I have compiled the changes with WinUAE and verified that A2065/slirp still works fine. There are no logical changes, only refactoring to make it possible for FS-UAE to use slirp via qemu-uae plugin, and also to make the slirp code independent from win32_uanenet.cpp.
> Refactored slirp to make it possible to use an alternative impl

- dlopen.cpp
- od-win32/caps/caps_win32.cpp
- od-win32/sysconfig.h
- od-win32/win32.cpp
- qemuvga/qemu.cpp
- uaenative.cpp
This patch unified WinUAE and FS-UAE plugin loading, including FS-UAE using the capsimg loading code from WinUAE. I have tested that WinUAE still loads both capsimg.dll and qemu-uae.dll correctly (both in plugins dir and alsongside winuae.exe).
> merged uae_dlopen_plugin implementations, unified capsimg support

- consolehook.cpp
I any case, the old code cannot work (probably unused...)
> consolehook: missing parameter (presumably supposed to be stdout)

- jit/codegen_x86.cpp
- jit/compemu_fpp.cpp
- jit/compemu_midfunc_x86.cpp
- jit/compemu_support.cpp
With these fixes (one of the commits is only a workaround), AmiKit boots - and what I have tested works fine - with 64-bit JIT and FPU JIT enabled.
> JIT: Fixes for 64-bit FPU JIT

- main.cpp
- od-win32/mman.cpp
It looks like the cpuboard_jitdirectompatible() check is reversed in main.cpp
(Based on bug report http://eab.abime.net/showpost.php?p=1043088&postcount=911)
- Please double-check that the fix is correct.
I also changed the code so error_log is only used when JIT was actually requested (FS-UAE shows error_log messages in the GUI).
> Fixed check for Blizzard cpuboard memtype in main.cpp

- od-win32/winuae_msvc14/winuae_msvc.vcxproj
This allows some more virtual address space to be used (outside the "contiguous region"), for example for Blizzard.
> changed baseaddress to 0x10000000

- include/uae/time.h
- od-win32/machdep/rpt.h
- od-win32/win32.cpp
- od-win32/winuae_msvc14/winuae_msvc.vcxproj
- od-win32/winuae_msvc14/winuae_msvc.vcxproj.filters
- support/time.cpp
This isn't a fix, but FS-UAE on Windows also needed the high-precision timing code from WinUAE. So I moved it out to a separate module. Would appreciated it if you merged this commit into WinUAE to avoid code duplication.
> move read_proceesor_time (and co) to support/time.cpp

- newcpu.cpp
When compiling with GCC and default warnings enabled, GCC complains about static functions that are not called anywhere. It would be nice to get rid of these warnings by disabling these unused functions (or maybe m68k_run_mmu() and/or exception2_handle() should be removed completely instead?). Thanks!
> Disable some unused functions

- jit/codegen_x86.cpp
this allows to parse the file with custom tools that expect a semicolon at the end of a statement.
additionally it makes the code look like C/C++ and not like BASIC.
> REX64: convert to function-type macro

- gencpu.cpp
While doing some experiments with BCD arithmetic corner cases I have noticed that the V flag isn't handled properly on the 030 -- it shouldn't be involved in the calculation (contrary to the 68000). I can't test how it performs on the 020, most likely the same, i.e. `xBCD_KEEPS_V_FLAG` should be changed to `2` after confirmation.
Tested & implemented on Hatari's `cpu/gencpu.c` and backported by hand, I hope I didn't miss anything. Tested on all possible combinations of `Z`, `C` and both byte operands (2 * 2 * 256 * 256 tests).
> Keep the V flag on the 68030

- gencpu.cpp
See #128, the V flag was cleared when it shouldn't in some cases. Verified on all possible combinations.
> Fix NBCD instruction

- cpummu30.cpp
- fpp.cpp
- scsi.cpp
First patch silences some compiler warnings when compiling with -Wsign-compare, and the second patch fixes the wrong if-statement in the getmsglen() function in scsi.cpp.
> Two small fixes

- cputest/main.c
When compiling with clang it will complain about
```
multiple unsequenced modifications to 'p' [-Wunsequenced]
```
This is because doing changes such as `variable++` twice or more on the same line the order of which one that happens first is undefined. This PR does the reads to two separate variables first to guarantee the ordering is correct.
> Fixed read order

- gencpu.cpp
- include/readcpu.h
- newcpu.cpp
There are currently a bunch of GCC compiler warnings when compiling the CPU code in Hatari. Here are the fixes to silence them.
> Silence some compiler warnings in the CPU code

- build68k.cpp
"char" is signed by default on many systems, so when using a "char"
variable as input to isspace(), which takes an "int" parameter, the
parameter gets sign-extended. Now in some libc implementations, the
isspace() function is implemented as a macro that directly indexes
an array for looking up the result - which might go wrong, of course,
if the byte values has the highest bit set. So when compiling Hatari
with Cygwin, there are the following compiler warnings:
.../build68k.c: In function ‘main’:
.../build68k.c:314:18: warning: array subscript has type ‘char’ [-Wchar-subscripts]
314 |   while (isspace(*opstrp))
|                  ^~~~~~~
.../build68k.c:319:18: warning: array subscript has type ‘char’ [-Wchar-subscripts]
319 |    if (!isspace (*osendp))
|                  ^~~~~~~ …
> Avoid using isspace() with signed characters

- .gitignore
- cputest/main.c
Until now the -ccrmask option was allowed to be either 0x00 or 0xff only, all other variants were non-working and caused error regardless if given CCR bit was masked or not.
Now the ccr_mask variable is used during validation tests too, so that only the unmasked bits of CCR are actually tested.
> cputest: make ccr_mask usable

- debug.cpp
- od-win32/win32gui.cpp
Visual debugger has been updated to consider changes to blitter debugger in 4.9.0.  A buffer overrun was causing garbage colors to be displayed.  Now that the DMA debugger "extra" field uses high bits to store extra blitter state, a side effect is that each channel of normal blits can have its own color.  I chose to give the D channel a different color to distinguish reads from writes.  For simplicity, line and fill mode channels show the same solid debug colors as 4.4.0.  Fast memory board support also fixed after new MAX_STANDARD_RAM_BOARDS constant was added in 4.9.0 (it was missing in a few places).
> Minor debugger and GUI fixes

- debug.cpp
- Initialize and clamp local maxhpos and maxvpos values if scanrate changes.
- Initialize "dma_rec->end" when recording DMA to prevent false hsync record if scanrate changes.
> Scanrate fix for visual debugger

- cpummu30.cpp
- cputest.cpp
- cputest/cputestgen.ini
- include/uae/types.h
- jit/compemu_support.cpp
- newcpu.cpp
Two small cosmetic patches, one to fix some typos, and one to fix some compiler warnings about 'void' functions returning a value.
> Fix typos and compiler warning

- newcpu.cpp
- "cacheholdingdata_valid" sometimes used as iterator; should not be init as boolean.
- Fix 060 "No Allocate Mode" CACR bit to a valid u32 value.
> Cache bit corrections

- cfgfile.cpp
Updates "bip_a4000()" to be consistent with "built_in_chipset_prefs()" so VSync TOD source is always used for A4000/A4000T.
> Update A4000(T) TOD source

- cfgfile.cpp
The new NVRAM path wasn't actually used in CD32/CDTV etc. configs, as they were still fetching the `data` path for the flashfile, instead.
This commit fixes that and sets those configs that have a flashfile, to use the nvram path for it instead.
> Use nvram path

- newcpu.cpp
Update DMA debugger record for 040+ to show instruction memory access, not data.
> Fix 040 instruction mem read

- od-win32/mman.cpp
ortgmem_type is defined having a size of MAX_RTG_BOARDS, but the loop uses MAX_RAM_BOARDS when going through it.
Since MAX_RAM_BOARDS and MAX_RTG_BOARDS happen to be the same (4) in WinUAE, it didn't have any effect. However, if those happen to be different (like in Amiberry, where MAX_RTG_BOARDS is set to 1), then this will cause undefined behavior after the first iteration.
> bugfix: loop for ortgmem_type should be for the number of MAX_RTG_BOARDS

- custom.cpp
- gencpu.cpp
- inputdevice.cpp
- Fix missing `#ifdef DEBUGGER` in a few places
- Fixed `decide_hdiw2` parameters when DEBUGGER is not available
- Removed redundant extra `break` statement in `intputdevice.cpp`
> Minor fixes

- debug.cpp
Amiga crash may cause vsync to be lost, causing dma_record[] overflow.
> Fix buffer overflow if VPOS out of range

- ide.cpp
- scsi.cpp
I noticed that setting the volume via mode select on ATAPI devices was not working and tracked it down to this.
Before ```scsi_emulate_cmd()``` is called for commands writing to the device the memcpy was using ```ide->data_size```.
Then ```ide->data_size``` is copied to ```scsi->data_len```.
The problem here is that by the time we get here, ```ide->data_size``` is 0 because it is decremented on every data write before the packet is processed here:
https://github.com/tonioni/WinUAE/blob/b2877eeb48e2a922f2a9ca50481e7d3ca16d0f5c/ide.cpp#L1365-L1373
```ide->data_offset``` is zeroed by ```atapi_set_size()``` well before the call to ```scsi_emulate_cmd()```
https://github.com/tonioni/WinUAE/blob/b2877eeb48e2a922f2a9ca50481e7d3ca16d0f5c/ide.cpp#L857-L861
So I thought ```ide->packet_data_size``` …
> ATAPI Write / Mode Select fix

- include/memory.h
GCC does not accept the same identifier used as both type and variable name "addrbank *addrbank;". Changing to struct addrbank fixes this (alternative fix is to change the type name to something like addrbank_t). I've tested that WinUAE builds fine with this change.
> addrbank gcc compatibility fix in include/memory.h

- a2091.cpp
- cpuboard.cpp
- include/a2091.h
- include/commpipe.h
- od-win32/threaddep/thread.h
Added () to sizeof where necessary, moved one function declaration to header file, made minor changes to a couple of header files so a2091.h can be included by cpuboard.cpp.
> GCC compatibility fixes for a2091

- framebufferboards.cpp
generic_fb_bank is unchanged, only moved further up to be able to remove the (at least for non-msvc compilers) incompatible extern declaration.
> framebufferboards: use DECLARE_MEMORY_FUNCTIONS and move definition up

- disk.cpp
When drive_insert is called from DISK_hsync, it is called with drv->newname as fname_in, causing invokation of _tcscpy with the same src and dst address (overlapping write), which may or may not be a problem, but it least isn't allowed (undefined behavior).
(Discovered by valgrind memchecker while debugging another problem)
> Fix overlapping _tcscpy write

- include/zfile.h
- zfile.cpp
In zcache_close, while freeing the linked list, the next item is freed instead of the current one.
(Additionally, adding a sizeof fix + remove double opening /* in header)
> zfile: Free the current list item, not the next (+ two minor fixes)

- include/tinyxml2.h
- tinyxml2.cpp
This upgrades `tinyxml2` from v8.0 to v11.0, which is the latest version.
No breaking changes from what I can see in my tests, and we get some fixes along the way.
> Upgrade tinyxml2 from v8.0 to v11.0
